/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers/index'
import { Route as PassesIndexRouteImport } from './routes/passes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AccommodationIndexRouteImport } from './routes/accommodation/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesIndexRoute = PassesIndexRouteImport.update({
  id: '/passes/',
  path: '/passes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationIndexRoute = AccommodationIndexRouteImport.update({
  id: '/accommodation/',
  path: '/accommodation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/accommodation/': typeof AccommodationIndexRoute
  '/events/': typeof EventsIndexRoute
  '/passes/': typeof PassesIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about': typeof AboutIndexRoute
  '/accommodation': typeof AccommodationIndexRoute
  '/events': typeof EventsIndexRoute
  '/passes': typeof PassesIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/about/': typeof AboutIndexRoute
  '/accommodation/': typeof AccommodationIndexRoute
  '/events/': typeof EventsIndexRoute
  '/passes/': typeof PassesIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/about/'
    | '/accommodation/'
    | '/events/'
    | '/passes/'
    | '/speakers/'
    | '/sponsors/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/about'
    | '/accommodation'
    | '/events'
    | '/passes'
    | '/speakers'
    | '/sponsors'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/about/'
    | '/accommodation/'
    | '/events/'
    | '/passes/'
    | '/speakers/'
    | '/sponsors/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AccommodationIndexRoute: typeof AccommodationIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PassesIndexRoute: typeof PassesIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes/': {
      id: '/passes/'
      path: '/passes'
      fullPath: '/passes/'
      preLoaderRoute: typeof PassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/': {
      id: '/accommodation/'
      path: '/accommodation'
      fullPath: '/accommodation/'
      preLoaderRoute: typeof AccommodationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AccommodationIndexRoute: AccommodationIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  PassesIndexRoute: PassesIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
